### ISSUE TITLE
URLerror

### ISSUE THREAD

**Issue by sph1r17** [bonaime/seedlink_plotter#26]
Hello,

I tried one both examples in readme: e.g. `seedlink-plotter -s "G_MBO:00BHZ" -b 10m --seedlink_server "rtserver.ipgp.fr:18000"  --line_plot`

And I get the following error:
```
Traceback (most recent call last):
  File "/Users/sph1r17/anaconda/bin/seedlink-plotter", line 11, in <module>
    load_entry_point('seedlink-plotter==0.1.0', 'console_scripts', 'seedlink-plotter')()
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/sph1r17/anaconda/lib/python3.6/site-packages/seedlink_plotter/seedlink_plotter.py", line 420
    except URLError, error:
```

**Comment by megies** [comment]
I'm not sure we support python 3..

**Comment by rsignell-usgs** [comment]
I can confirm that creating the py2.7 environment above works.    But also converting the code to python3 using `2to3` works.
